gateway:
  port: "6666"
  tcp_filters:
    enabled:
      - tcp_limit
    configs:
      tcp_limit:
        max_conn: 100
  http_filters:
    enabled: []
    configs: {}
  decoder:
    max_body: 4096
  encoder: {}
  transformer:
    enabled:
      - testT
    configs:
      testT: {}
  pool:
    max_conn: 64
    min_idle: 4
    dial_timeout: 3s
    borrow_timeout: 10s
    idle_timeout: 60s
    wait_timeout: 5s
